#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/ice/cm/guts-man/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/ice/cm/guts-man/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/ice/cm/guts-man/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/ice/cm/guts-man/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /Users/ice/cm/guts-man/node_modules/tabtab/.completions/slss.zsh ]] && . /Users/ice/cm/guts-man/node_modules/tabtab/.completions/slss.zsh
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ice/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/ice/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ice/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/ice/google-cloud-sdk/completion.zsh.inc'; fi
