#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Homebrew
if [ -d "/usr/local/bin" ]; then
  # zprofile will also do following `export PATH=...`
  export PATH=/usr/local/sbin:/usr/local/bin:$PATH
  if [ -d "/Applications" ]; then
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  fi
fi

if which direnv > /dev/null; then eval "$(direnv hook zsh)"; fi

[[ -f /usr/local/bin/pyenv ]] && eval "$(pyenv init -)"

# rbenv
# if [ -d "$HOME/.rbenv/bin" ]; then
#   export PATH="$HOME/.rbenv/bin:$PATH"
#   if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
# fi

# nodenv
# if [ -d "$HOME/.nodenv/bin" ]; then
#   export PATH="$HOME/.nodenv/bin:$PATH"
#   if which nodenv > /dev/null; then
#     # if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
#     eval "$(nodenv init -)"
#     export PATH=$PATH:`npm bin -g`
#   fi
# fi

# aws-cli
if [ -d "${HOME}/aws-cli" ]; then
  export PATH="$PATH:${HOME}/aws-cli"
fi

## awsume
if [ -d "${HOME}/.local/bin" ]; then
  export PATH=$PATH:$HOME/.local/bin
fi

# The next line updates PATH for the Google Cloud SDK.
# if [ -f "${HOME}/google-cloud-sdk/path.zsh.inc" ]; then
#   . "${HOME}/google-cloud-sdk/path.zsh.inc"
# fi

# The next line enables shell command completion for gcloud.
# if [ -f "${HOME}/google-cloud-sdk/completion.zsh.inc" ]; then
#   . "${HOME}/google-cloud-sdk/completion.zsh.inc"
# fi

# brew install mysql-client
# if [ -d "/usr/local/opt/mysql-client/bin" ]; then
#   export PATH="$PATH:/usr/local/opt/mysql-client/bin"
# fi

# https://postgresapp.com/
# if [ -d "/Applications/Postgres.app/Contents/Versions/latest/bin" ]; then
#   export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
# fi

# Rancher Desktop / Docker
if [ -d "${HOME}/.rd/bin" ]; then
  # export PATH="$HOME/.rd/bin:$PATH"
  export PATH="$PATH:$HOME/.rd/bin"
fi

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/ise.yohei/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# Claude Code
if [ -d "${HOME}/.claude/local" ]; then
  # alias claude="${HOME}/.claude/local/claude"
  # Warning: Local installation not accessible
  # Fix: Alias exists but points to invalid target: ${HOME}/.claude/local/claude. Update alias: alias claude="~/.claude/local/claude"
  alias claude="~/.claude/local/claude"
  # echo 'export PATH="$HOME/.claude/local:$PATH"'
fi

# # 1Password CLI
# if [ -f "${HOME}/.config/op/plugins.sh" ]; then
#   source "${HOME}/.config/op/plugins.sh"
#   ## SSH
#   export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
# fi
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
